controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint1_position_controller:
      type: passthrough_controller/PassthroughController

    joint2_position_controller:
      type: passthrough_controller/PassthroughController

    position_controller:
      type: passthrough_controller/PassthroughController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

# First-level controllers
joint1_position_controller:
  ros__parameters:
    interfaces: ["joint1/position"]


joint2_position_controller:
  ros__parameters:
    interfaces: ["joint2/position"]


# Second-level controller
position_controller:
  ros__parameters:
    interfaces:
      - joint1_position_controller/joint1/position
      - joint2_position_controller/joint2/position

# Third-level controllers
forward_position_controller:
  ros__parameters:
    joints:
      - position_controller/joint1_position_controller/joint1
      - position_controller/joint2_position_controller/joint2
    interface_name: position
