controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pid_controller_left_wheel_joint:
      type: pid_controller/PidController

    pid_controller_right_wheel_joint:
      type: pid_controller/PidController

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController


pid_controller_left_wheel_joint:
  ros__parameters:

    dof_names:
      - left_wheel_joint

    command_interface: velocity

    reference_and_state_interfaces:
      - velocity

    gains:
      # control the velocity, no d term
      left_wheel_joint: {"p": 0.5, "i": 2.5, "d": 0.0, "i_clamp_min": -20.0, "i_clamp_max": 20.0, "antiwindup": true, "feedforward_gain": 0.95}

pid_controller_right_wheel_joint:
  ros__parameters:

    dof_names:
      - right_wheel_joint

    command_interface: velocity

    reference_and_state_interfaces:
      - velocity

    gains:
      # control the velocity, no d term
      right_wheel_joint: {"p": 0.5, "i": 2.5, "d": 0.0, "i_clamp_min": -20.0, "i_clamp_max": 20.0, "antiwindup": true, "feedforward_gain": 0.95}

diffbot_base_controller:
  ros__parameters:

    left_wheel_names: ["pid_controller_left_wheel_joint/left_wheel_joint"]
    right_wheel_names: ["pid_controller_right_wheel_joint/right_wheel_joint"]

    wheel_separation: 0.10
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.015

    # we have velocity feedback
    position_feedback: false

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    # set publish_limited_velocity to true for visualization
    publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN
