controller_manager:
  ros__parameters:
    update_rate: 2  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController


forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position
