publisher_forward_velocity_controller:
  ros__parameters:

    controller_name: "forward_velocity_controller"
    wait_sec_between_publish: 5

    goal_names: ["pos1", "pos2", "pos3", "pos4", "pos5", "pos6"]
    pos1: [-0.5, 0.5]
    pos2: [0.5, -0.5]
    pos3: [0.0, 0.0]
    pos4: [0.5, -0.5]
    pos5: [-0.5, 0.5]
    pos6: [0.0, 0.0]
