controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

    bicycle_steering_controller:
      type: bicycle_steering_controller/BicycleSteeringController


ackermann_steering_controller:
  ros__parameters:

    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: false
    rear_wheels_names: [rear_right_wheel_joint, rear_left_wheel_joint]
    front_wheels_names: [left_steering_hinge_joint, right_steering_hinge_joint]
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true

    wheelbase: 0.325
    front_wheel_track: 0.2
    rear_wheel_track: 0.2
    front_wheels_radius: 0.05
    rear_wheels_radius: 0.05

bicycle_steering_controller:
  ros__parameters:

    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: false
    rear_wheels_names: [rear_wheel_joint]
    front_wheels_names: [steering_axis_joint]

    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true


    wheelbase: 0.325
    front_wheel_radius: 0.05
    rear_wheel_radius: 0.05






# diffbot_base_controller:
#   ros__parameters:
#     left_wheel_names: ["left_wheel_joint"]
#     right_wheel_names: ["right_wheel_joint"]

#     wheel_separation: 0.10
#     #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
#     wheel_radius: 0.015

#     wheel_separation_multiplier: 1.0
#     left_wheel_radius_multiplier: 1.0
#     right_wheel_radius_multiplier: 1.0

#     publish_rate: 50.0
#     odom_frame_id: odom
#     base_frame_id: base_link
#     pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
#     twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

#     open_loop: true
#     enable_odom_tf: true

#     cmd_vel_timeout: 0.5
#     #publish_limited_velocity: true
#     use_stamped_vel: false
#     #velocity_rolling_window_size: 10

#     # Velocity and acceleration limits
#     # Whenever a min_* is unspecified, default to -max_*
#     linear.x.has_velocity_limits: true
#     linear.x.has_acceleration_limits: true
#     linear.x.has_jerk_limits: false
#     linear.x.max_velocity: 1.0
#     linear.x.min_velocity: -1.0
#     linear.x.max_acceleration: 1.0
#     linear.x.max_jerk: 0.0
#     linear.x.min_jerk: 0.0

#     angular.z.has_velocity_limits: true
#     angular.z.has_acceleration_limits: true
#     angular.z.has_jerk_limits: false
#     angular.z.max_velocity: 1.0
#     angular.z.min_velocity: -1.0
#     angular.z.max_acceleration: 1.0
#     angular.z.min_acceleration: -1.0
#     angular.z.max_jerk: 0.0
#     angular.z.min_jerk: 0.0
