/rrbot_1/publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "rrbot_1/position_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [0.785, 0.785]
    pos2:
      positions: [0.0, 0.0]
    pos3:
      positions: [-0.785, -0.785]
    pos4:
      positions: [0.0, 0.0]

    joints:
      - rrbot_1_joint1
      - rrbot_1_joint2

    check_starting_point: false
    starting_point_limits:
      joint1: [-0.1,0.1]
      joint2: [-0.1,0.1]


/rrbot_2/publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "rrbot_2/position_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:
      positions: [-0.785, 0.0]
    pos2:
      positions: [0.0, -0.785]
    pos3:
      positions: [+0.785, -1.57]
    pos4:
      positions: [+1.57, -0.785]

    joints:
      - rrbot_2_joint1
      - rrbot_2_joint2

    check_starting_point: false
    starting_point_limits:
      joint1: [-0.1,0.1]
      joint2: [-0.1,0.1]
