/rrbot_1/publisher_forward_position_controller:
  ros__parameters:


    publish_topic: "forward_position_controller/commands"
    wait_sec_between_publish: 5

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.785, 0.785]
    pos2: [0.0, 0.0]
    pos3: [-0.785, -0.785]
    pos4: [0.0, 0.0]


/rrbot_2/publisher_forward_position_controller:
  ros__parameters:

    publish_topic: "forward_position_controller/commands"
    wait_sec_between_publish: 5

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [-0.785, 0.0]
    pos2: [0.0, -0.785]
    pos3: [+0.785, -1.57]
    pos4: [+1.57, -0.785]
