controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    gpio_controller:
      type: gpio_controllers/GpioCommandController


forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position

gpio_controller:
  ros__parameters:
    gpios:
      - flange_analog_IOs
      - flange_vacuum
    command_interfaces:
      flange_analog_IOs:
        - interfaces:
          - analog_output1
      flange_vacuum:
        - interfaces:
          - vacuum
