controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


forward_position_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
      - joint2
    interface_name: position

gpio_controller:
  ros__parameters:
    type: gpio_controllers/GpioCommandController
    gpios:
      - flange_analog_IOs
      - flange_vacuum
    command_interfaces:
      flange_analog_IOs:
        - interfaces:
          - analog_output1
      flange_vacuum:
        - interfaces:
          - vacuum
