name: Rolling Semi-Binary Build
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '23 1 * * *'

jobs:
  semi_binary_rolling:
    name: semi binary build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: rolling, ROS_REPO: main}
          - {ROS_DISTRO: rolling, ROS_REPO: testing}
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
