name: ROS Lint
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, cppcheck, lint_cmake]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@v0.2
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: foxy
        linter: ${{ matrix.linter }}
        package-name:
          ros2_control_demo_hardware
          ros2_control_demo_description
          ros2_control_demo_bringup
          ros2_control_demos

  ament_lint_cpplint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [cpplint]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@v0.2
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: foxy
        linter: cpplint
        arguments: "--filter=-whitespace/newline"
        package-name:
          ros2_control_demo_hardware
          ros2_control_demo_description
          ros2_control_demo_bringup
          ros2_control_demos
