name: Humble Binary Build
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  pull_request:
    branches:
      - humble
  push:
    branches:
      - humble
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'

jobs:
  binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    with:
      ros_distro: humble
      upstream_workspace: ros2_control_demos-not-released.humble.repos
      ref_for_scheduled_build: humble
