name: Humble Semi-Binary Build
# description: 'Build & test that compiles the main dependencies from source.'

on:
  pull_request:
    branches:
      - humble
  push:
    branches:
      - humble
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '33 1 * * *'

jobs:
  semi_binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    with:
      ros_distro: humble
      upstream_workspace: ros2_control_demos.humble.repos
      ref_for_scheduled_build: humble
