name: Build Humble Dockerfile
# description: builds the dockerfile contained within the repo

on:
  pull_request:
    branches:
      - humble
    paths:
      - '**.hpp'
      - '**.cpp'
      - Dockerfile/**
      - '.github/workflows/humble-docker-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - '**.xacro'
      - '**.py'
      - '**.yaml'
      - 'ros2_control_demos.humble.repos'
  push:
    branches:
      - humble
    paths:
      - '**.hpp'
      - '**.cpp'
      - Dockerfile/**
      - '.github/workflows/humble-docker-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - '**.xacro'
      - '**.py'
      - '**.yaml'
      - 'ros2_control_demos.humble.repos'
  schedule:
    # Run every morning to detect broken dependencies
    - cron: '40 1 * * MON-FRI'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: humble
    - name: Build the Docker image
      run: docker build --file Dockerfile/Dockerfile --tag ros2_control_demos_humble --build-arg ROS_DISTRO=humble .
