name: Jazzy Binary Build
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  pull_request:
    branches:
      - jazzy
    paths:
      - '**.hpp'
      - '**.cpp'
      - '.github/workflows/jazzy-binary-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - '**.xacro'
      - '**.py'
      - '**.yaml'
      - 'ros2_control_demos-not-released.jazzy.repos'
      - '**.xml'
  push:
    branches:
      - jazzy
    paths:
      - '**.hpp'
      - '**.cpp'
      - '.github/workflows/jazzy-binary-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - '**.xacro'
      - '**.py'
      - '**.yaml'
      - 'ros2_control_demos-not-released.jazzy.repos'
      - '**.xml'
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * MON-FRI'

jobs:
  binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_REPO: [main, testing]
    with:
      ros_distro: jazzy
      ros_repo: ${{ matrix.ROS_REPO }}
      upstream_workspace: ros2_control_demos-not-released.jazzy.repos
      ref_for_scheduled_build: jazzy
