name: Reviewer lottery
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  reviewer-lottery:
    runs-on: ubuntu-latest
    if: ${{ ! contains(fromJSON('["dependabot[bot]", "mergify[bot]"]'), github.actor) }}
    steps:
    - uses: actions/checkout@v4
    - uses: uesteibar/reviewer-lottery@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
