name: Rolling Semi-Binary Build
# description: 'Build & test that compiles the main dependencies from source.'

on:
  pull_request:
    branches:
      - master
    paths:
      - '**.hpp'
      - '**.cpp'
      - '.github/workflows/rolling-semi-binary-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - '**.xacro'
      - '**.py'
      - '**.yaml'
      - 'ros2_control_demos.rolling.repos'
      - '**.xml'
  push:
    branches:
      - master
    paths:
      - '**.hpp'
      - '**.cpp'
      - '.github/workflows/rolling-semi-binary-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - '**.xacro'
      - '**.py'
      - '**.yaml'
      - 'ros2_control_demos.rolling.repos'
      - '**.xml'
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '33 1 * * MON-FRI'

jobs:
  semi_binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling, kilted, jazzy]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: testing
      upstream_workspace: ros2_control_demos.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: master
