name: Rolling Semi-Binary Build
# description: 'Build & test that compiles the main dependencies from source.'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '33 1 * * *'

jobs:
  semi_binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling]
        ROS_REPO: [main, testing]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: ${{ matrix.ROS_REPO }}
      upstream_workspace: ros2_control_demos.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: master
