controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - joint1
      - joint2

forward_velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - joint1
      - joint2

forward_acceleration_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
      - joint2
    interface_name: acceleration

forward_illegal1_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
    interface_name: position

forward_illegal2_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint2
    interface_name: position
